# Generated by Django 6.0.3 on 2026-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
